name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Qt runtime deps (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libxkbcommon-x11-0 \
            libxcb-xinerama0

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          pytest -q

      - name: Run tests (macOS)
        if: runner.os == 'macOS'
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          pytest -q

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          pytest -q
